// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  //this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 790, height: 816 })
    await driver.findElement(By.css("button")).click()
    assert(await driver.switchTo().alert().getText() == "Success")
  })
})
